// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace universal_scheduler_be.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260615163355_AddSkillAndServiceTypePermissions")]
    partial class AddSkillAndServiceTypePermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceBayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceBayId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("TechnicianId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Infrastructure.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Infrastructure.Entities.Dealership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dealerships");
                });

            modelBuilder.Entity("Infrastructure.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000001"),
                            Description = "View all appointments (staff/admin)",
                            Name = "appointments:read"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000002"),
                            Description = "View only the signed-in user's appointments",
                            Name = "appointments:read:own"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000003"),
                            Description = "Create and update appointments",
                            Name = "appointments:write"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000004"),
                            Description = "Manage users and roles",
                            Name = "users:manage"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000005"),
                            Description = "View dealerships (admin only)",
                            Name = "dealerships:read"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000006"),
                            Description = "Create and update dealerships (admin only)",
                            Name = "dealerships:write"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000007"),
                            Description = "View skills (admin only)",
                            Name = "skills:read"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000008"),
                            Description = "Create and delete skills (admin only)",
                            Name = "skills:write"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-000000000009"),
                            Description = "View service types (admin only)",
                            Name = "servicetypes:read"
                        },
                        new
                        {
                            Id = new Guid("a1000001-0000-4000-8000-00000000000a"),
                            Description = "Create, update, and deactivate service types (admin only)",
                            Name = "servicetypes:write"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000001"),
                            Description = "Full system access",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000002"),
                            Description = "Day-to-day scheduling (all appointments)",
                            Name = "Staff"
                        },
                        new
                        {
                            Id = new Guid("b2000001-0000-4000-8000-000000000003"),
                            Description = "Self-service: own appointments only",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000008")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000009")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000001"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-00000000000a")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000002"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000002"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000003"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("b2000001-0000-4000-8000-000000000003"),
                            PermissionId = new Guid("a1000001-0000-4000-8000-000000000003")
                        });
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceBay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.ToTable("ServiceBays");
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.HasIndex("SkillId");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("Infrastructure.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Infrastructure.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId");

                    b.ToTable("Technicians");
                });

            modelBuilder.Entity("Infrastructure.Entities.TechnicianSkill", b =>
                {
                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid");

                    b.HasKey("TechnicianId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("TechnicianSkills");
                });

            modelBuilder.Entity("Infrastructure.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Infrastructure.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Infrastructure.Entities.Appointment", b =>
                {
                    b.HasOne("Infrastructure.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.ServiceBay", "ServiceBay")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceBayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.ServiceType", "ServiceType")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Technician", "Technician")
                        .WithMany("Appointments")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ServiceBay");

                    b.Navigation("ServiceType");

                    b.Navigation("Technician");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Infrastructure.Entities.RolePermission", b =>
                {
                    b.HasOne("Infrastructure.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceBay", b =>
                {
                    b.HasOne("Infrastructure.Entities.Dealership", "Dealership")
                        .WithMany("ServiceBays")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceType", b =>
                {
                    b.HasOne("Infrastructure.Entities.Dealership", "Dealership")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Skill", "Skill")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Infrastructure.Entities.Technician", b =>
                {
                    b.HasOne("Infrastructure.Entities.Dealership", "Dealership")
                        .WithMany("Technicians")
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealership");
                });

            modelBuilder.Entity("Infrastructure.Entities.TechnicianSkill", b =>
                {
                    b.HasOne("Infrastructure.Entities.Skill", "Skill")
                        .WithMany("TechnicianSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Entities.Technician", "Technician")
                        .WithMany("TechnicianSkills")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("Infrastructure.Entities.User", b =>
                {
                    b.HasOne("Infrastructure.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Infrastructure.Entities.Vehicle", b =>
                {
                    b.HasOne("Infrastructure.Entities.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Infrastructure.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Infrastructure.Entities.Dealership", b =>
                {
                    b.Navigation("ServiceBays");

                    b.Navigation("ServiceTypes");

                    b.Navigation("Technicians");
                });

            modelBuilder.Entity("Infrastructure.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Infrastructure.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceBay", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Infrastructure.Entities.ServiceType", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Infrastructure.Entities.Skill", b =>
                {
                    b.Navigation("ServiceTypes");

                    b.Navigation("TechnicianSkills");
                });

            modelBuilder.Entity("Infrastructure.Entities.Technician", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TechnicianSkills");
                });

            modelBuilder.Entity("Infrastructure.Entities.Vehicle", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
